name: CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        prisma-version: [4.7.0, 4.8.0, latest]
        node-version: [16, 18]

    name: Node ${{ matrix.node_version }} with Prisma ${{ matrix.prisma-version }}
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          prisma-version: ${{ matrix.prisma-version }}
          cache: "yarn"

      - name: ğŸ— Swap Prisma version to ~${{ matrix.prisma-version }}
        run: |
          sed -i -E 's|"prisma": ".*"|"prisma": "~"${{ matrix.prisma-version }}"|g' package.json
          sed -i -E 's|"\@prisma/client": ".*"|"\@prisma/client": "~${{ matrix.prisma-version }}"|g' package.json
          sed -i -E 's|"\@prisma/generator-helper": ".*"|"\@prisma/generator-helper": "~${{ matrix.prisma-version }}"|g' package.json
          sed -i -E 's|"\@prisma/internals": ".*"|"\@prisma/internals": "~${{ matrix.prisma-version }}"|g' package.json

      - name: ğŸ“¥ Install dependencies
        run: yarn install

      - name: ğŸ§ª Run tests
        run: yarn test

